<?
	class TextUtil
	{
	    function getRandomPhrase ($str = null)
	    {
	        $a = array (
	               'How\'s it goin\'?',
	               'I\'m just chillin\'',
	               'Where\'s Jack Bauer?',
        	       'What\'s for lunch?',
	               'You like my yellow shirt?',
	               'Keepin\' it real since April',
	               '5 + 5 = 10',
	               'You complete me',
	               'Show me the $$$',
	               'The other, other white meat',
	               'I\'m the son of rage and love',
	               'Flavor Fla',
	               'Don\'t smoke crack',
	               'Don\'t eat green meat',
	               'Frumunda what?',
	               'Messin With Sasquatch',
	               'Skookum = Bigfoot',
	               'Skookum > you',
	               'Don\'t hassle the Hoff',
	               'Poo is brown',
	               'Crazy is as crazy does',
	               '&lt;TABLE&gt; is so 1999',
	               'R E D R U M',
	               'I quit huffin\' glue',
	               'Listen to Ignite',
	               'Ashtray Monument',
	               'Read <a target="_blank" href="http://Valleywag.com">Valleywag</a>',
	               'Do ya Tweet?',
	               'What\'s your major malfunction',
	               'I kissed a yeti',
	               'I found Loch Ness',
	               'Deez',
	               'Powered by craigslist',
	               'I hate Whole Foods',
	               'BBQ sauce please',
	               'Thank you drive thru',
	               'UFO\'s are real',
	               'That\'s quite a conundrum',
	               'I read <a target="_blank" href="http://www.techcrunch.com">TechCrunch</a>',
	               'Help me help you',
                   'I\'ll be right back',
                   'Hello Sidney',
                   'I like Megadeth',
                   'Balls are best',
                   'Hello Sidney',
                   'Always double down on 11',
                   'You\'re so money',
                   'You\'re like a bear man',
                   'I love Veronnica Mars',
        	       'Dave Matthews sucks!',
        	       'Slash is my hero',
        	       '<a target="_blank" href="http://www.juliaallison.com">Juila Allison</a> should blog more',
	               'Tivo is the shit!',
	               'MS Windows can suck it!',
	               'Do you Micro-Hoo!?',
	               'MySpace is a garbage can',
	               'How tall are you, private?',
	               'Watch Bill Maher',
	               'Hmmmm, Cheetos',
	               '7 days...',
	               '...And Out Come the Wolves',
	               'Amazon Prime rules',
	               'Tastes like chicken',
	               '<a target="_blank" href="http://www.fuzz.com">Vote Goat</a>',
	               'Every rose has its thorns',
	               'You\'re so dreamy',
	               'Death by stereo',
	               'Metallica used to rock',
	               'I\'m "Web 1.9"',
	               'We all go a little mad sometimes',
	               'I have no legs - I have no legs',
	               'Blade should\'ve won an Oscar',
	               'I miss Van Damm',
	               'I spread disease like a dog',
	               'Killing is my business',
	               'I see dead people',
	               '... and busines is good',
	               'The warheads will all rust in peace',
	               'Fo\' shizzle',
	               'Stupid box model',
	               'Netscape - good riddance',
	               'Toto RULES!',	        
	           );
	           
           shuffle ($a);
           return $a[0];
	    }
	}
?>